import json

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Solución - Tarea #4: Estadística para Ciencia de los Datos\n",
    "\n",
    "## Introducción\n",
    "\n",
    "El presente documento constituye la solución detallada de la cuarta tarea del curso de Estadística para Ciencia de los Datos. Se abordan dos problemas fundamentales: el análisis de varianza (ANOVA) para comparar medias poblacionales y las estrategias de imputación de datos faltantes. La metodología empleada sigue un enfoque riguroso y sistemático, implementando los cálculos desde cero sin recurrir a bibliotecas especializadas para el análisis ANOVA."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importación de bibliotecas necesarias\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import scipy.stats as stats\n",
    "from typing import List, Tuple, Dict\n",
    "\n",
    "# Configuración para visualización\n",
    "plt.style.use('seaborn-v0_8-darkgrid')\n",
    "plt.rcParams['figure.figsize'] = (10, 6)\n",
    "plt.rcParams['font.size'] = 12"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Parte 1: Análisis de Varianza (ANOVA)\n",
    "\n",
    "### 1.1 Planteamiento del Problema\n",
    "\n",
    "Se busca determinar si existe diferencia significativa en el peso medio de las aguas residuales por galón descargadas por cuatro plantas químicas. Los datos proporcionados corresponden a cinco observaciones aleatorias de cada planta, expresadas en libras por galón.\n",
    "\n",
    "### 1.2 Hipótesis\n",
    "\n",
    "**Hipótesis nula ($H_0$):** Las medias poblacionales de los desechos de las cuatro plantas son iguales.\n",
    "$$H_0: \\mu_A = \\mu_B = \\mu_C = \\mu_D$$\n",
    "\n",
    "**Hipótesis alternativa ($H_1$):** Al menos una media poblacional difiere de las demás.\n",
    "$$H_1: \\text{Al menos una } \\mu_i \\neq \\mu_j \\text{ para } i \\neq j$$\n",
    "\n",
    "**Nivel de significancia:** $\\alpha = 0.05$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Datos del problema\n",
    "datosPlantaA = [1.65, 1.72, 1.50, 1.37, 1.60]\n",
    "datosPlantaB = [1.70, 1.85, 1.46, 1.46, 1.80]\n",
    "datosPlantaC = [1.40, 1.75, 1.38, 1.38, 1.55]\n",
    "datosPlantaD = [2.10, 1.95, 1.65, 1.65, 1.88]\n",
    "\n",
    "# Organización de datos en estructura DataFrame\n",
    "datosPlantas = pd.DataFrame({\n",
    "    'PlantaA': datosPlantaA,\n",
    "    'PlantaB': datosPlantaB,\n",
    "    'PlantaC': datosPlantaC,\n",
    "    'PlantaD': datosPlantaD\n",
    "})\n",
    "\n",
    "print(\"Datos de Desechos por Planta (libras/galón):\")\n",
    "print(datosPlantas)\n",
    "print(\"\\nEstadísticas Descriptivas:\")\n",
    "print(datosPlantas.describe())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1.3 Implementación del ANOVA\n",
    "\n",
    "El análisis de varianza descompone la variabilidad total de los datos en dos componentes:\n",
    "- **Variabilidad entre grupos (SSB):** Variación debida a las diferencias entre las medias de los grupos\n",
    "- **Variabilidad dentro de grupos (SSW):** Variación debida a las diferencias individuales dentro de cada grupo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Paso 1: Cálculo de medias y parámetros básicos\n",
    "numeroGrupos = 4  # k = número de plantas\n",
    "observacionesPorGrupo = 5  # n = observaciones por planta\n",
    "numeroTotalObservaciones = numeroGrupos * observacionesPorGrupo  # N = total de observaciones\n",
    "\n",
    "# Convertir datos a formato largo para cálculos\n",
    "todosLosDatos = []\n",
    "grupoPertenencia = []\n",
    "\n",
    "for columna in datosPlantas.columns:\n",
    "    todosLosDatos.extend(datosPlantas[columna].values)\n",
    "    grupoPertenencia.extend([columna] * observacionesPorGrupo)\n",
    "\n",
    "# Cálculo de medias por grupo\n",
    "mediasGrupos = {}\n",
    "for planta in datosPlantas.columns:\n",
    "    mediasGrupos[planta] = np.mean(datosPlantas[planta])\n",
    "\n",
    "# Media global\n",
    "mediaGlobal = np.mean(todosLosDatos)\n",
    "\n",
    "print(\"Medias por Planta:\")\n",
    "for planta, media in mediasGrupos.items():\n",
    "    print(f\"{planta}: {media:.4f} libras/galón\")\n",
    "print(f\"\\nMedia Global: {mediaGlobal:.4f} libras/galón\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Paso 2: Cálculo de Sumas de Cuadrados\n",
    "\n",
    "# Suma de Cuadrados Total (SST)\n",
    "sumaCuadradosTotal = 0\n",
    "for valor in todosLosDatos:\n",
    "    sumaCuadradosTotal += (valor - mediaGlobal) ** 2\n",
    "\n",
    "# Suma de Cuadrados Entre Grupos (SSB)\n",
    "sumaCuadradosEntreGrupos = 0\n",
    "for planta in datosPlantas.columns:\n",
    "    sumaCuadradosEntreGrupos += observacionesPorGrupo * (mediasGrupos[planta] - mediaGlobal) ** 2\n",
    "\n",
    "# Suma de Cuadrados Dentro de Grupos (SSW)\n",
    "sumaCuadradosDentroGrupos = 0\n",
    "for planta in datosPlantas.columns:\n",
    "    for valor in datosPlantas[planta]:\n",
    "        sumaCuadradosDentroGrupos += (valor - mediasGrupos[planta]) ** 2\n",
    "\n",
    "# Verificación: SST = SSB + SSW\n",
    "print(f\"Suma de Cuadrados Total (SST): {sumaCuadradosTotal:.6f}\")\n",
    "print(f\"Suma de Cuadrados Entre Grupos (SSB): {sumaCuadradosEntreGrupos:.6f}\")\n",
    "print(f\"Suma de Cuadrados Dentro de Grupos (SSW): {sumaCuadradosDentroGrupos:.6f}\")\n",
    "print(f\"\\nVerificación SST = SSB + SSW: {sumaCuadradosTotal:.6f} = {sumaCuadradosEntreGrupos + sumaCuadradosDentroGrupos:.6f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Paso 3: Cálculo de Grados de Libertad y Cuadrados Medios\n",
    "\n",
    "# Grados de libertad\n",
    "gradosLibertadEntreGrupos = numeroGrupos - 1\n",
    "gradosLibertadDentroGrupos = numeroTotalObservaciones - numeroGrupos\n",
    "gradosLibertadTotal = numeroTotalObservaciones - 1\n",
    "\n",
    "# Cuadrados medios\n",
    "cuadradoMedioEntreGrupos = sumaCuadradosEntreGrupos / gradosLibertadEntreGrupos\n",
    "cuadradoMedioDentroGrupos = sumaCuadradosDentroGrupos / gradosLibertadDentroGrupos\n",
    "\n",
    "print(\"Grados de Libertad:\")\n",
    "print(f\"Entre grupos: {gradosLibertadEntreGrupos}\")\n",
    "print(f\"Dentro de grupos: {gradosLibertadDentroGrupos}\")\n",
    "print(f\"Total: {gradosLibertadTotal}\")\n",
    "print(\"\\nCuadrados Medios:\")\n",
    "print(f\"Cuadrado Medio Entre Grupos (MSB): {cuadradoMedioEntreGrupos:.6f}\")\n",
    "print(f\"Cuadrado Medio Dentro de Grupos (MSW): {cuadradoMedioDentroGrupos:.6f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Paso 4: Cálculo del Estadístico F y Valor Crítico\n",
    "\n",
    "# Estadístico F\n",
    "estadisticoF = cuadradoMedioEntreGrupos / cuadradoMedioDentroGrupos\n",
    "\n",
    "# Valor crítico de F\n",
    "nivelSignificancia = 0.05\n",
    "valorCriticoF = stats.f.ppf(1 - nivelSignificancia, gradosLibertadEntreGrupos, gradosLibertadDentroGrupos)\n",
    "\n",
    "# Valor p\n",
    "valorP = 1 - stats.f.cdf(estadisticoF, gradosLibertadEntreGrupos, gradosLibertadDentroGrupos)\n",
    "\n",
    "print(f\"Estadístico F calculado: {estadisticoF:.4f}\")\n",
    "print(f\"Valor crítico F({gradosLibertadEntreGrupos},{gradosLibertadDentroGrupos}) al {int((1-nivelSignificancia)*100)}%: {valorCriticoF:.4f}\")\n",
    "print(f\"Valor p: {valorP:.6f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Tabla ANOVA completa\n",
    "tablaAnova = pd.DataFrame({\n",
    "    'Fuente de Variación': ['Entre Grupos', 'Dentro de Grupos', 'Total'],\n",
    "    'Suma de Cuadrados': [sumaCuadradosEntreGrupos, sumaCuadradosDentroGrupos, sumaCuadradosTotal],\n",
    "    'Grados de Libertad': [gradosLibertadEntreGrupos, gradosLibertadDentroGrupos, gradosLibertadTotal],\n",
    "    'Cuadrado Medio': [cuadradoMedioEntreGrupos, cuadradoMedioDentroGrupos, '-'],\n",
    "    'Estadístico F': [f\"{estadisticoF:.4f}\", '-', '-'],\n",
    "    'Valor p': [f\"{valorP:.6f}\", '-', '-']\n",
    "})\n",
    "\n",
    "print(\"\\nTabla ANOVA:\")\n",
    "print(tablaAnova.to_string(index=False))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1.4 Decisión Estadística y Conclusión\n",
    "\n",
    "La decisión se toma comparando el estadístico F calculado con el valor crítico de la distribución F, o alternativamente, comparando el valor p con el nivel de significancia α."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Decisión estadística\n",
    "print(\"DECISIÓN ESTADÍSTICA:\")\n",
    "print(\"=\"*50)\n",
    "\n",
    "if estadisticoF > valorCriticoF:\n",
    "    decision = \"RECHAZAR H₀\"\n",
    "    explicacion = \"El estadístico F calculado es mayor que el valor crítico\"\n",
    "else:\n",
    "    decision = \"NO RECHAZAR H₀\"\n",
    "    explicacion = \"El estadístico F calculado es menor que el valor crítico\"\n",
    "\n",
    "print(f\"\\nCriterio 1 - Comparación de F:\")\n",
    "print(f\"F calculado ({estadisticoF:.4f}) vs F crítico ({valorCriticoF:.4f})\")\n",
    "print(f\"Decisión: {decision} - {explicacion}\")\n",
    "\n",
    "print(f\"\\nCriterio 2 - Valor p:\")\n",
    "print(f\"Valor p ({valorP:.6f}) vs α ({nivelSignificancia})\")\n",
    "if valorP < nivelSignificancia:\n",
    "    print(f\"Decisión: RECHAZAR H₀ - El valor p es menor que α\")\n",
    "else:\n",
    "    print(f\"Decisión: NO RECHAZAR H₀ - El valor p es mayor que α\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(\"CONCLUSIÓN:\")\n",
    "if estadisticoF > valorCriticoF:\n",
    "    print(\"Existe evidencia estadística suficiente para concluir que hay diferencias\")\n",
    "    print(\"significativas en el peso medio de las aguas residuales por galón\")\n",
    "    print(\"descargadas entre al menos dos de las cuatro plantas químicas.\")\n",
    "else:\n",
    "    print(\"No existe evidencia estadística suficiente para concluir que hay\")\n",
    "    print(\"diferencias significativas en el peso medio de las aguas residuales\")\n",
    "    print(\"por galón descargadas entre las cuatro plantas químicas.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualización de los datos\n",
    "plt.figure(figsize=(12, 8))\n",
    "\n",
    "# Subplot 1: Boxplot\n",
    "plt.subplot(2, 2, 1)\n",
    "datosPlantas.boxplot()\n",
    "plt.title('Distribución de Desechos por Planta', fontsize=14)\n",
    "plt.ylabel('Libras por Galón', fontsize=12)\n",
    "plt.xlabel('Planta', fontsize=12)\n",
    "plt.grid(True, alpha=0.3)\n",
    "\n",
    "# Subplot 2: Gráfico de medias con intervalos de confianza\n",
    "plt.subplot(2, 2, 2)\n",
    "plantas = list(mediasGrupos.keys())\n",
    "medias = list(mediasGrupos.values())\n",
    "erroresEstandar = []\n",
    "for planta in plantas:\n",
    "    se = np.std(datosPlantas[planta], ddof=1) / np.sqrt(observacionesPorGrupo)\n",
    "    erroresEstandar.append(se)\n",
    "\n",
    "plt.errorbar(plantas, medias, yerr=[1.96*se for se in erroresEstandar], \n",
    "             fmt='o-', capsize=5, capthick=2, markersize=8)\n",
    "plt.axhline(y=mediaGlobal, color='r', linestyle='--', label='Media Global')\n",
    "plt.title('Medias por Planta con IC 95%', fontsize=14)\n",
    "plt.ylabel('Libras por Galón', fontsize=12)\n",
    "plt.xlabel('Planta', fontsize=12)\n",
    "plt.legend()\n",
    "plt.grid(True, alpha=0.3)\n",
    "\n",
    "# Subplot 3: Distribución F\n",
    "plt.subplot(2, 2, 3)\n",
    "x = np.linspace(0, 10, 1000)\n",
    "y = stats.f.pdf(x, gradosLibertadEntreGrupos, gradosLibertadDentroGrupos)\n",
    "plt.plot(x, y, 'b-', label=f'F({gradosLibertadEntreGrupos},{gradosLibertadDentroGrupos})')\n",
    "plt.axvline(x=valorCriticoF, color='r', linestyle='--', label=f'Valor crítico = {valorCriticoF:.3f}')\n",
    "plt.axvline(x=estadisticoF, color='g', linestyle='-', linewidth=2, label=f'F calculado = {estadisticoF:.3f}')\n",
    "plt.fill_between(x[x > valorCriticoF], y[x > valorCriticoF], alpha=0.3, color='red', label='Región de rechazo')\n",
    "plt.title('Distribución F y Región de Rechazo', fontsize=14)\n",
    "plt.xlabel('Valor F', fontsize=12)\n",
    "plt.ylabel('Densidad', fontsize=12)\n",
    "plt.legend()\n",
    "plt.grid(True, alpha=0.3)\n",
    "\n",
    "# Subplot 4: Gráfico de puntos por grupo\n",
    "plt.subplot(2, 2, 4)\n",
    "for i, planta in enumerate(plantas):\n",
    "    valores = datosPlantas[planta]\n",
    "    plt.scatter([i]*len(valores), valores, alpha=0.6, s=100)\n",
    "    plt.scatter(i, mediasGrupos[planta], color='red', s=200, marker='_', linewidth=3)\n",
    "plt.axhline(y=mediaGlobal, color='black', linestyle='--', alpha=0.5, label='Media Global')\n",
    "plt.xticks(range(len(plantas)), plantas)\n",
    "plt.title('Observaciones Individuales por Planta', fontsize=14)\n",
    "plt.ylabel('Libras por Galón', fontsize=12)\n",
    "plt.xlabel('Planta', fontsize=12)\n",
    "plt.legend()\n",
    "plt.grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Parte 2: Estrategias de Imputación de Datos Faltantes\n",
    "\n",
    "### 2.1 Introducción\n",
    "\n",
    "La presencia de datos faltantes constituye uno de los desafíos más frecuentes en ciencia de datos. La imputación de datos es el proceso mediante el cual se estiman y reemplazan los valores ausentes en un conjunto de datos, permitiendo así el aprovechamiento completo de la información disponible y evitando sesgos en los análisis posteriores."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2.2 Estrategia 1: Imputación por Media, Mediana o Moda\n",
    "\n",
    "#### Descripción\n",
    "\n",
    "Esta estrategia consiste en reemplazar los valores faltantes con medidas de tendencia central calculadas a partir de los valores observados. La elección entre media, mediana o moda depende del tipo de variable y la distribución de los datos.\n",
    "\n",
    "- **Media:** Para variables numéricas con distribución aproximadamente normal\n",
    "- **Mediana:** Para variables numéricas con distribución sesgada o presencia de valores atípicos\n",
    "- **Moda:** Para variables categóricas o discretas\n",
    "\n",
    "#### Ventajas\n",
    "- Implementación simple y rápida\n",
    "- Preserva el tamaño de la muestra\n",
    "- No introduce valores fuera del rango observado\n",
    "\n",
    "#### Desventajas\n",
    "- Reduce la variabilidad de los datos\n",
    "- No considera las relaciones entre variables\n",
    "- Puede introducir sesgo si los datos no faltan aleatoriamente\n",
    "\n",
    "#### Casos de Uso Recomendados\n",
    "- Cuando el porcentaje de datos faltantes es bajo (< 5%)\n",
    "- En análisis exploratorios preliminares\n",
    "- Cuando se requiere una solución rápida y los datos faltan completamente al azar (MCAR)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ejemplo de Imputación por Media/Mediana/Moda\n",
    "np.random.seed(42)\n",
    "\n",
    "# Crear conjunto de datos de ejemplo con valores faltantes\n",
    "datosEjemplo = pd.DataFrame({\n",
    "    'edad': [25, 30, np.nan, 45, 35, np.nan, 28, 52, 41, 33],\n",
    "    'salario': [35000, 42000, 38000, np.nan, 45000, 51000, np.nan, 62000, 48000, 40000],\n",
    "    'categoria': ['A', 'B', 'A', np.nan, 'B', 'C', 'A', np.nan, 'B', 'C']\n",
    "})\n",
    "\n",
    "print(\"Datos originales con valores faltantes:\")\n",
    "print(datosEjemplo)\n",
    "\n",
    "# Imputación por media\n",
    "datosImputadosMedia = datosEjemplo.copy()\n",
    "datosImputadosMedia['edad'].fillna(datosImputadosMedia['edad'].mean(), inplace=True)\n",
    "datosImputadosMedia['salario'].fillna(datosImputadosMedia['salario'].mean(), inplace=True)\n",
    "\n",
    "# Imputación por mediana\n",
    "datosImputadosMediana = datosEjemplo.copy()\n",
    "datosImputadosMediana['edad'].fillna(datosImputadosMediana['edad'].median(), inplace=True)\n",
    "datosImputadosMediana['salario'].fillna(datosImputadosMediana['salario'].median(), inplace=True)\n",
    "\n",
    "# Imputación por moda\n",
    "datosImputadosModa = datosEjemplo.copy()\n",
    "datosImputadosModa['categoria'].fillna(datosImputadosModa['categoria'].mode()[0], inplace=True)\n",
    "\n",
    "print(\"\\n\\nImputación por Media:\")\n",
    "print(f\"Edad media imputada: {datosEjemplo['edad'].mean():.2f}\")\n",
    "print(f\"Salario medio imputado: {datosEjemplo['salario'].mean():.2f}\")\n",
    "\n",
    "print(\"\\nImputación por Mediana:\")\n",
    "print(f\"Edad mediana imputada: {datosEjemplo['edad'].median():.2f}\")\n",
    "print(f\"Salario mediano imputado: {datosEjemplo['salario'].median():.2f}\")\n",
    "\n",
    "print(\"\\nImputación por Moda:\")\n",
    "print(f\"Categoría modal imputada: {datosEjemplo['categoria'].mode()[0]}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2.3 Estrategia 2: Imputación por K-Vecinos Más Cercanos (KNN)\n",
    "\n",
    "#### Descripción\n",
    "\n",
    "La imputación por K-Vecinos Más Cercanos (K-Nearest Neighbors, KNN) es una técnica que estima los valores faltantes basándose en la similitud con otras observaciones completas. Para cada valor faltante, el algoritmo:\n",
    "\n",
    "1. Identifica las K observaciones más similares (vecinos) que tienen valores completos\n",
    "2. Calcula la distancia entre observaciones usando las variables disponibles\n",
    "3. Imputa el valor faltante como el promedio (ponderado o no) de los valores de los K vecinos más cercanos\n",
    "\n",
    "#### Ventajas\n",
    "- Considera las relaciones multivariadas entre las características\n",
    "- Puede capturar patrones no lineales en los datos\n",
    "- Más precisa que la imputación por media cuando existen correlaciones fuertes\n",
    "\n",
    "#### Desventajas\n",
    "- Computacionalmente costosa para conjuntos de datos grandes\n",
    "- Sensible a la escala de las variables (requiere normalización)\n",
    "- La elección de K puede afectar significativamente los resultados\n",
    "- No funciona bien con alta dimensionalidad\n",
    "\n",
    "#### Casos de Uso Recomendados\n",
    "- Cuando existe correlación entre las variables\n",
    "- Conjuntos de datos de tamaño pequeño a mediano\n",
    "- Cuando los datos faltan de manera aleatoria (MAR)\n",
    "- En problemas donde la similitud entre observaciones es significativa"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ejemplo de Imputación KNN (implementación conceptual simplificada)\n",
    "from sklearn.impute import KNNImputer\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# Crear datos de ejemplo con correlación\n",
    "np.random.seed(42)\n",
    "n = 100\n",
    "x1 = np.random.normal(50, 10, n)\n",
    "x2 = 2 * x1 + np.random.normal(0, 5, n)  # Variable correlacionada\n",
    "x3 = np.random.normal(30, 5, n)\n",
    "\n",
    "datosKnn = pd.DataFrame({\n",
    "    'variable1': x1,\n",
    "    'variable2': x2,\n",
    "    'variable3': x3\n",
    "})\n",
    "\n",
    "# Introducir valores faltantes de forma aleatoria\n",
    "indicesFaltantes = np.random.choice(n, 20, replace=False)\n",
    "datosKnn.loc[indicesFaltantes[:10], 'variable1'] = np.nan\n",
    "datosKnn.loc[indicesFaltantes[10:15], 'variable2'] = np.nan\n",
    "datosKnn.loc[indicesFaltantes[15:], 'variable3'] = np.nan\n",
    "\n",
    "print(\"Resumen de datos faltantes:\")\n",
    "print(datosKnn.isnull().sum())\n",
    "\n",
    "# Normalizar datos para KNN\n",
    "scaler = StandardScaler()\n",
    "datosNormalizados = scaler.fit_transform(datosKnn)\n",
    "\n",
    "# Aplicar KNN Imputer\n",
    "imputadorKnn = KNNImputer(n_neighbors=5)\n",
    "datosImputadosKnn = imputadorKnn.fit_transform(datosNormalizados)\n",
    "datosImputadosKnn = scaler.inverse_transform(datosImputadosKnn)\n",
    "\n",
    "# Convertir de vuelta a DataFrame\n",
    "datosKnnCompletos = pd.DataFrame(datosImputadosKnn, columns=datosKnn.columns)\n",
    "\n",
    "# Comparar valores originales e imputados\n",
    "print(\"\\nComparación de algunos valores imputados:\")\n",
    "for idx in indicesFaltantes[:5]:\n",
    "    print(f\"\\nObservación {idx}:\")\n",
    "    print(f\"Variable 1 - Original: {x1[idx]:.2f}, Imputado: {datosKnnCompletos.loc[idx, 'variable1']:.2f}\")\n",
    "    print(f\"Variable 2 - Original: {x2[idx]:.2f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2.4 Estrategia 3: Imputación Múltiple por Ecuaciones Encadenadas (MICE)\n",
    "\n",
    "#### Descripción\n",
    "\n",
    "La Imputación Múltiple por Ecuaciones Encadenadas (Multivariate Imputation by Chained Equations, MICE) es una técnica sofisticada que aborda la incertidumbre inherente en la imputación de datos. El proceso MICE involucra:\n",
    "\n",
    "1. **Imputación inicial:** Se realiza una imputación simple (por ejemplo, media) para todos los valores faltantes\n",
    "2. **Modelado iterativo:** Para cada variable con valores faltantes:\n",
    "   - Se ajusta un modelo de regresión usando las demás variables como predictores\n",
    "   - Se predicen los valores faltantes usando este modelo\n",
    "   - Se añade variabilidad estocástica a las predicciones\n",
    "3. **Iteración:** Se repite el proceso hasta convergencia\n",
    "4. **Múltiples imputaciones:** Se genera múltiples conjuntos de datos imputados para capturar la incertidumbre\n",
    "\n",
    "#### Ventajas\n",
    "- Maneja la incertidumbre en las imputaciones\n",
    "- Considera las relaciones complejas entre variables\n",
    "- Proporciona estimaciones válidas de la varianza\n",
    "- Puede manejar diferentes tipos de variables (continuas, categóricas, etc.)\n",
    "\n",
    "#### Desventajas\n",
    "- Computacionalmente intensiva\n",
    "- Requiere especificación cuidadosa de los modelos\n",
    "- Asume que los datos faltan de manera aleatoria (MAR)\n",
    "- La convergencia puede ser difícil de evaluar\n",
    "\n",
    "#### Casos de Uso Recomendados\n",
    "- Análisis inferenciales donde la incertidumbre es crítica\n",
    "- Conjuntos de datos con patrones complejos de valores faltantes\n",
    "- Cuando se requieren intervalos de confianza válidos\n",
    "- Investigación académica y estudios clínicos"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ejemplo conceptual de MICE (usando sklearn's IterativeImputer)\n",
    "from sklearn.experimental import enable_iterative_imputer\n",
    "from sklearn.impute import IterativeImputer\n",
    "\n",
    "# Crear datos con patrones complejos\n",
    "np.random.seed(42)\n",
    "n = 200\n",
    "\n",
    "# Variables con relaciones no lineales\n",
    "variableX = np.random.normal(100, 15, n)\n",
    "variableY = 50 + 0.5 * variableX + 0.01 * variableX**2 + np.random.normal(0, 10, n)\n",
    "variableZ = 30 * np.sin(variableX/50) + np.random.normal(0, 5, n)\n",
    "\n",
    "datosMice = pd.DataFrame({\n",
    "    'X': variableX,\n",
    "    'Y': variableY,\n",
    "    'Z': variableZ\n",
    "})\n",
    "\n",
    "# Introducir patrón MAR de valores faltantes\n",
    "# Los valores de Y faltan más cuando X es alto\n",
    "probabilidadFaltanteY = 1 / (1 + np.exp(-(variableX - 100) / 10))\n",
    "faltantesY = np.random.random(n) < probabilidadFaltanteY * 0.3\n",
    "datosMice.loc[faltantesY, 'Y'] = np.nan\n",
    "\n",
    "# Los valores de Z faltan aleatoriamente\n",
    "faltantesZ = np.random.choice(n, 30, replace=False)\n",
    "datosMice.loc[faltantesZ, 'Z'] = np.nan\n",
    "\n",
    "print(\"Patrón de datos faltantes:\")\n",
    "print(datosMice.isnull().sum())\n",
    "print(f\"\\nPorcentaje total de datos faltantes: {datosMice.isnull().sum().sum() / (n * 3) * 100:.1f}%\")\n",
    "\n",
    "# Aplicar MICE (IterativeImputer en sklearn)\n",
    "imputadorMice = IterativeImputer(\n",
    "    max_iter=10,\n",
    "    random_state=42,\n",
    "    initial_strategy='mean'\n",
    ")\n",
    "\n",
    "# Generar múltiples imputaciones\n",
    "numeroImputaciones = 5\n",
    "imputacionesMultiples = []\n",
    "\n",
    "for i in range(numeroImputaciones):\n",
    "    imputadorTemp = IterativeImputer(\n",
    "        max_iter=10,\n",
    "        random_state=42 + i,\n",
    "        initial_strategy='mean'\n",
    "    )\n",
    "    datosImputados = imputadorTemp.fit_transform(datosMice)\n",
    "    imputacionesMultiples.append(pd.DataFrame(datosImputados, columns=datosMice.columns))\n",
    "\n",
    "# Calcular estadísticas agregadas\n",
    "mediasImputaciones = pd.concat([df.mean() for df in imputacionesMultiples], axis=1).T\n",
    "print(\"\\nMedias de las múltiples imputaciones:\")\n",
    "print(mediasImputaciones)\n",
    "print(\"\\nVariabilidad entre imputaciones:\")\n",
    "print(mediasImputaciones.std())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2.5 Comparación Visual de las Estrategias"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Comparación visual de estrategias\n",
    "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
    "\n",
    "# Datos para visualización\n",
    "np.random.seed(42)\n",
    "nVisualizacion = 50\n",
    "xVis = np.random.normal(50, 10, nVisualizacion)\n",
    "yVis = 2 * xVis + np.random.normal(0, 8, nVisualizacion)\n",
    "\n",
    "# Introducir valores faltantes\n",
    "faltantesVis = np.random.choice(nVisualizacion, 15, replace=False)\n",
    "xVisFaltantes = xVis.copy()\n",
    "yVisFaltantes = yVis.copy()\n",
    "xVisFaltantes[faltantesVis[:8]] = np.nan\n",
    "yVisFaltantes[faltantesVis[8:]] = np.nan\n",
    "\n",
    "# Subplot 1: Datos originales con faltantes\n",
    "ax1 = axes[0, 0]\n",
    "mascara = ~(np.isnan(xVisFaltantes) | np.isnan(yVisFaltantes))\n",
    "ax1.scatter(xVisFaltantes[mascara], yVisFaltantes[mascara], alpha=0.6, s=50)\n",
    "ax1.set_title('Datos con Valores Faltantes', fontsize=14)\n",
    "ax1.set_xlabel('Variable X')\n",
    "ax1.set_ylabel('Variable Y')\n",
    "ax1.grid(True, alpha=0.3)\n",
    "\n",
    "# Subplot 2: Imputación por media\n",
    "ax2 = axes[0, 1]\n",
    "xMediaImputado = np.where(np.isnan(xVisFaltantes), np.nanmean(xVisFaltantes), xVisFaltantes)\n",
    "yMediaImputado = np.where(np.isnan(yVisFaltantes), np.nanmean(yVisFaltantes), yVisFaltantes)\n",
    "ax2.scatter(xVis[mascara], yVis[mascara], alpha=0.6, s=50, label='Originales')\n",
    "ax2.scatter(xMediaImputado[~mascara], yMediaImputado[~mascara], \n",
    "           alpha=0.8, s=80, marker='s', color='red', label='Imputados')\n",
    "ax2.set_title('Imputación por Media', fontsize=14)\n",
    "ax2.set_xlabel('Variable X')\n",
    "ax2.set_ylabel('Variable Y')\n",
    "ax2.legend()\n",
    "ax2.grid(True, alpha=0.3)\n",
    "\n",
    "# Subplot 3: Comparación de distribuciones\n",
    "ax3 = axes[1, 0]\n",
    "ax3.hist(yVis, bins=15, alpha=0.5, label='Original', density=True)\n",
    "ax3.hist(yMediaImputado, bins=15, alpha=0.5, label='Media', density=True)\n",
    "ax3.set_title('Comparación de Distribuciones', fontsize=14)\n",
    "ax3.set_xlabel('Variable Y')\n",
    "ax3.set_ylabel('Densidad')\n",
    "ax3.legend()\n",
    "ax3.grid(True, alpha=0.3)\n",
    "\n",
    "# Subplot 4: Tabla resumen\n",
    "ax4 = axes[1, 1]\n",
    "ax4.axis('off')\n",
    "resumenEstrategias = pd.DataFrame({\n",
    "    'Estrategia': ['Media/Mediana', 'KNN', 'MICE'],\n",
    "    'Complejidad': ['Baja', 'Media', 'Alta'],\n",
    "    'Precisión': ['Baja', 'Media-Alta', 'Alta'],\n",
    "    'Velocidad': ['Muy Rápida', 'Media', 'Lenta'],\n",
    "    'Maneja Incertidumbre': ['No', 'No', 'Sí']\n",
    "})\n",
    "tabla = ax4.table(cellText=resumenEstrategias.values,\n",
    "                  colLabels=resumenEstrategias.columns,\n",
    "                  cellLoc='center',\n",
    "                  loc='center',\n",
    "                  bbox=[0, 0, 1, 1])\n",
    "tabla.auto_set_font_size(False)\n",
    "tabla.set_fontsize(10)\n",
    "tabla.scale(1, 2)\n",
    "ax4.set_title('Resumen Comparativo de Estrategias', fontsize=14, pad=20)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Conclusiones\n",
    "\n",
    "### Sobre el Análisis ANOVA\n",
    "\n",
    "El análisis de varianza realizado sobre los datos de desechos de las cuatro plantas químicas reveló diferencias estadísticamente significativas entre al menos dos de las plantas. Este resultado sugiere que los procesos de tratamiento o las características operativas difieren entre las instalaciones, lo cual tiene implicaciones importantes para la gestión ambiental y el cumplimiento normativo.\n",
    "\n",
    "### Sobre las Estrategias de Imputación\n",
    "\n",
    "Las tres estrategias de imputación presentadas ofrecen soluciones complementarias para el tratamiento de datos faltantes:\n",
    "\n",
    "1. **Imputación por tendencia central:** Apropiada para análisis exploratorios rápidos y situaciones con pocos datos faltantes\n",
    "2. **Imputación KNN:** Óptima cuando existen relaciones entre variables que pueden aprovecharse\n",
    "3. **Imputación MICE:** La opción más robusta para análisis inferenciales que requieren cuantificar la incertidumbre\n",
    "\n",
    "La elección de la estrategia debe basarse en:\n",
    "- El mecanismo de pérdida de datos (MCAR, MAR, MNAR)\n",
    "- El porcentaje de valores faltantes\n",
    "- Los objetivos del análisis\n",
    "- Los recursos computacionales disponibles\n",
    "- La importancia de cuantificar la incertidumbre"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

# Save the notebook to a file
with open('Solucion_Tarea4_EstadisticaParaCienciaDeLosDatos.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, ensure_ascii=False, indent=1)

print("Notebook successfully created: Solucion_Tarea4_EstadisticaParaCienciaDeLosDatos.ipynb")